sudo: required
services:
  - docker

before_install:
  - docker build -t jk64/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jk64/react-test npm test

after_success:
  - docker build -t jk64/complex-client ./client
  - docker build -t jk64/complex-nginx ./nginx
  - docker build -t jk64/complex-server ./server
  - docker build -t jk64/complex-worker ./worker
  # Log in docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push image to docker hub
  - docker build jk64/complex-client
  - docker build jk64/complex-nginx
  - docker build jk64/complex-server
  - docker build jk64/complex-worker