sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t jk64/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jk64/react-test npm test

after_success:
  - docker build -t jk64/complex-client ./client
  - docker build -t jk64/complex-nginx ./nginx
  - docker build -t jk64/complex-server ./server
  - docker build -t jk64/complex-worker ./worker
  # Log in docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push image to docker hub
  - docker push jk64/complex-client
  - docker push jk64/complex-nginx
  - docker push jk64/complex-server
  - docker push jk64/complex-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-west-1
  app: complex-docker
  env: ComplexDocker-env
  bucket_name: elasticbeanstalk-us-west-1-306476627547
  bucket_path: complex-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY